#!/bin/sh

# Prefer neovim if available
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" vimdiff="nvim -d" oldvim="/usr/bin/vim" oldvdiff="/usr/bin/vimdiff"

# Git aliases
alias g="git"
alias y="yadm"
alias dfe="yadm enter nvim"

# Verbosity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv"

# ls replacement
if [ -x "$(command -v exa)" ]; then
	alias ll="exa -lh -g --icons"
	alias lla="ll -a"
fi

# Quick edit common config files
alias \
	cfz="nvim ~/.config/zsh/.zshrc" \
	cfza="nvim ~/.config/zsh/zaliasrc" \
	cfv="nvim ~/.config/nvim/init.vim" \
	cft="nvim ~/.tmux.conf.local" \
	chx="nvim ~/.xinitrc" \
	chp="nvim ~/.profile" \
	chxp="nvim ~/.xprofile"

# Common apps
alias \
	n="n -Ax" \
	ls="exa" \
	ml="neomutt" # ml = mail

# Common commands
alias \
	q="exit" \
	ka="killall" \
	yt="youtube-dl" \
	upgr="yay -Syu" \
	se="sudo -e" \
	tas="tmux attach-session" \
	ta="tmux attach || tmux new-session" \
	td="tmux detach"

# zellij
alias \
	zl="zellij" \
	ze="zellij edit" \
	zr="zellij run" \
	za="zellij_attach" \
	zd="zellij_delete"
