#!/bin/bash

zellij_attach() {
	if [ -n "$1" ]; then
		zellij attach "$1"
	else
		session=$(_select_zellij_session)
		if [[ -n "$session" ]]; then
			zellij attach "$session"
		else
			echo "No session to select"
		fi
	fi
}

zellij_delete() {
	if [ -n "$1" ]; then
		zellij delete-session "$1"
	else
		session=$(_select_zellij_session)
		if [[ -n "$session" ]]; then
			zellij delete-session "$session"
		else
			echo "No session to select"
		fi
	fi
}

_select_zellij_session() {
	ZJ_SESSIONS=$(zellij list-sessions | awk '{print $1}' | sed -r "s/\x1b\[[0-9;]*[a-zA-Z]//g")
	NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

	if [ "${NO_SESSIONS}" -ge 1 ]; then
		session="$(echo "${ZJ_SESSIONS}" | fzf --info=inline --height $((NO_SESSIONS + 1)) --reverse)"
		if [[ -n "$session" ]]; then
			echo "$session"
		fi
	else
		echo ""
	fi
}
