#!/bin/bash

zellij_attach() {
	if [ -n "$1" ]; then
		zellij attach "$1"
	else
		ZJ_SESSIONS=$(zellij list-sessions | awk '{print $1}' | sed -r "s/\x1b\[[0-9;]*[a-zA-Z]//g")
		NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

		if [ "${NO_SESSIONS}" -ge 2 ]; then
			session="$(echo "${ZJ_SESSIONS}" | fzf --info=inline --height $((NO_SESSIONS + 1)) --reverse)"
			if [[ ! -z "$session" ]]; then
				zellij attach "$session"
			fi
		else
			zellij attach -c
		fi
	fi

}
