#!/usr/bin/env bash
source $HOME/.owl4ce_var

sed -s -i 's_geometry =.*_geometry = "350x6-20+60"_' "$DUNST_DIR"/dunstrc

sed -s -i 's_anchor:.*_anchor: south;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
sed -s -i 's_location:.*_location: south;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
sed -s -i 's_y-offset:.*_y-offset: -3%;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi

sed -i '131s_<right>.*_<right>10</right>_' $OB_CONFIG
sed -i '130s_<left>.*_<left>10</left>_' $OB_CONFIG
sed -i '129s_<bottom>.*_<bottom>10</bottom>_' $OB_CONFIG
sed -i '128s_<top>.*_<top>55</top>_' $OB_CONFIG
