#!/usr/bin/env bash
source $HOME/.ik_var

# Notification Daemon
deadd-notification-center &>/dev/null &
# Wallpaper Setter
nitrogen --restore &>/dev/null
# Panel
tint2 -c "$TINT2_CONF" &>/dev/null &
# Compositor
# picom --config /home/ichirou2910/.config/picom/picom.conf --experimental-backends &>/dev/null &
