local harpoon = require("harpoon")
local bufnr = vim.api.nvim_get_current_buf()

vim.keymap.set("n", "1", function()
    harpoon:list():select(1)
end, { buffer = bufnr })
vim.keymap.set("n", "2", function()
    harpoon:list():select(2)
end, { buffer = bufnr })
vim.keymap.set("n", "3", function()
    harpoon:list():select(3)
end, { buffer = bufnr })
vim.keymap.set("n", "4", function()
    harpoon:list():select(4)
end, { buffer = bufnr })
