#!/usr/bin/env bash
source $HOME/.owl4ce_var

noterr() { $EXNOTIFY_SEND -u low -r 11 "Install scrot!"; exit 1; }
type -p "scrot" &> /dev/null || noterr
OUTPUT=""

{
    [[ ! -d "$SAVE_DIR/Screenshots" ]] && mkdir -p "$SAVE_DIR/Screenshots" || :
    [[ "$1" = "delay" ]] && read -rt ".1" <> <(:) || :
    # scrot -q "$QUALITY" -e "mv '\$f' \"$SAVE_DIR/Screenshots\"" &> /dev/null

    scrot -q "$QUALITY" -e 'mv $f /tmp/' &> /dev/null && \

    for CURRENT in /tmp/*_scrot*.png; do
        CURRENT="$(echo $CURRENT | awk -F'/tmp/' '{print $2}' | awk -F'.png' '{print $1}')"
    done

    if [ $1 = "save" ]; then
        mv /tmp/$CURRENT.png $SAVE_DIR/Screenshots 
        OUTPUT="$SAVE_DIR/Screenshots/$CURRENT.png"
    else
        OUTPUT="/tmp/$CURRENT.png"
    fi

    xclip -selection clipboard -target image/png -i "$OUTPUT"

    rm -f /tmp/*_scrot*.png &> /dev/null

    $EXNOTIFY_SEND -r 11 -i "$NOTIF_SS_ICON" -u low "Screenshot" "Picture acquired!"
} &
