#!/usr/bin/env bash
export LC_ALL=POSIX LANG=POSIX
. "${HOME}/.ik_var"

noterr() {
	$EXNOTIFY_SEND -u low -r 11 "Install flameshot!"
	exit 1
}
type -p "flameshot" &>/dev/null || noterr

{
	[[ ! -d "$SAVE_DIR/Screenshots" ]] && mkdir -p "$SAVE_DIR/Screenshots"

	if [[ "$1" = "save" ]]; then
		flameshot screen -r -p "$SAVE_DIR/Screenshots"
	else
		flameshot screen -r -c
	fi
} &
