#!/usr/bin/env sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#
# ---
source $HOME/.owl4ce_var

# there was once a pulseaudio here

# UI Appearance
( "$VISMOD_DIR/refresh" && "$OB_TRAY" ) &> /dev/null

# Compositor
picom --experimental-backends --config ~/.config/picom/picom.conf &

# Authentication Agent - PolicyKit
lxpolkit &> /dev/null &

# Start MPD player (+notification-sender)
"$MPD_TCD"
